server:
  port: 6001
spring:
  application:
    name: PATIENT_SERVICE

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    hostname: localhost